# Generated by Django 5.1 on 2024-09-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_remove_realisateur_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisateur',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
    ]
